# Generated by Django 4.2.20 on 2025-03-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='identifier',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
