# Generated by Django 4.2.20 on 2025-04-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contact_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ticketmodel'),
        ),
    ]
