# Generated by Django 4.2.20 on 2025-05-02 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_message_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=30),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.CharField(choices=[('Administrador', 'Administrador'), ('attendant', 'attendant')], max_length=50)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Pause', 'Pause')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.agent'),
        ),
    ]
