# Generated by Django 4.2.20 on 2025-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_ticketmodel_user_alter_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('attendant', 'Attendant')], max_length=50),
        ),
    ]
